name: Run Mocha Tests (Weekly)

on:
  schedule:
    - cron: '0 9 * * 1'  # Toda segunda-feira às 09:00 UTC
  workflow_dispatch:      # Permite execução manual também

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: yarn install

      - name: Executar testes com Mocha
        run: yarn test
